defaults:
  - _self_
  - preset: example
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 42
exp_name: "ocr_training"

checkpoint_path: null
minified_json: False
